### ISSUE TITLE
Is there a non-script/plain Debian apt config available?

### ISSUE THREAD

**Issue by villasenor** [balena-io/etcher#3681]
- **Etcher version:** Latest
- **Operating system and architecture:** Debian
- **Image flashed:** n/a
- **Do you see any meaningful error information in the DevTools?** n/a

Hi team - thanks for an awesome project! I went to go run my ansible script that installs Balena Etcher and noticed that it no longer works! Turns out you switched to Cloudsmith - no worries. I am trying to figure out the new GPG key and apt config. Seeing as I'm using Ansible to do this, I don't want Ansible downloading a random bash script and running it. It's also a bit scary to blindly run random bash from the internet 😄  Where can I find the plain config that doesn't need a bash script? PPA config would also work.

For reference, this is what my ansible used to look like:
```
- name: Add Etcher Repo
  apt_repository:
    repo: deb https://deb.etcher.io stable etcher
    state: present
    filename: etcher
    update_cache: true
```

Thanks!
