### ISSUE TITLE
Release hash sums for AppImage in "latest-linux.yml" gone

### ISSUE THREAD

**Issue by TwizzyDizzy** [balena-io/etcher#4103]
- **Etcher version:** not relevant for this issue
- **Operating system and architecture:** not relevant for this issue
- **Image flashed:** not relevant for this issue
- **What do you think should have happened:** the release artifact `latest-linux.yml` should have containted the base64 encoded sha512sum of the `.AppImage` release artifact
- **What happened:** Up until release `1.18.8`, the `latest-linux.yml` release artifact contained the base64 encoded sha512sum of the `.AppImage` release artifact, but from version `1.18.9` on, the hash sum for the `.AppImage` does not seem to be released as artifact anymore. The `latest-linux.yml` now contains the base64 encoded sha512sum of the 64 bit debian package. Unfortunately, also no other `.yml` file contains a hash sum for the `.AppImage` artifact.
- **Do you see any meaningful error information in the DevTools?** not relevant

Up until `1.18.8` - `latest-linux.yml`:
```
version: 1.18.8
files:
  - url: balenaEtcher-1.18.8-x64.AppImage
    sha512: oy0igwNmAjuv3Fb74KySK2scsQYMOWqg1QoQOqe9Qr9r+/HoGBoAIQ0DCUu4cj5KcnWqhC0emoXQvOVC64Kt3A==
    size: 99670674
    blockMapSize: 105126
path: balenaEtcher-1.18.8-x64.AppImage
sha512: oy0igwNmAjuv3Fb74KySK2scsQYMOWqg1QoQOqe9Qr9r+/HoGBoAIQ0DCUu4cj5KcnWqhC0emoXQvOVC64Kt3A==
releaseDate: '2023-04-26T09:42:25.874Z'
stagingPercentage: "100"
```

From `1.18.9` - `latest-linux.yml`:
```
version: 1.18.9
files:
  - url: balena-etcher_1.18.9_amd64.deb
    sha512: rF9LPcOlqgOSD8lc99Gj/BgMZuPRxCa558/6K8sNebqLQiHoBfWy12uGoUnX8AJ0m/+XOmfGssFs9cyaxFdPMg==
    size: 90103074
path: balena-etcher_1.18.9_amd64.deb
sha512: rF9LPcOlqgOSD8lc99Gj/BgMZuPRxCa558/6K8sNebqLQiHoBfWy12uGoUnX8AJ0m/+XOmfGssFs9cyaxFdPMg==
releaseDate: '2023-07-12T08:53:38.340Z'
stagingPercentage: "100"
```

I can haz hash sums for `.AppImage` again? 🥺

Cheers
Thomas
